### ISSUE TITLE
It would be nice to be able to replace the back-reference character 

### ISSUE THREAD

**Issue by garyo** [micromark/micromark-extension-gfm-footnote#2]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

In my Chrome browser, the character "↩" renders as a sort of emoji -- a 3d blue square with the "back" arrow in it. This looks out of place, especially in dark mode. I see this character is hard-coded in footer.js in the footer() function.

It would be nice for a user to be able to change that to something that looks more in line with the rest of the text. In my case I'd probably use "⮐" or similar.

### Solution

Add an option to allow use of any character for this.

### Alternatives

Just replace ↩ with ⮐ in the source, if you agree it looks better.

**Comment by wooorm** [comment]
See https://github.com/syntax-tree/mdast-util-to-hast/issues/69
